version: '3.9'

services:
  database:
    command:
      - postgres
      - -c
      - wal_level=logical
    env_file:
      - ./.env
    image: supabase/postgres:0.13.0
    ports:
      - 5432:5432 # FIXME: Development
    volumes:
      - postgresql_data_volume:/var/lib/postgresql/data

volumes:
  postgresql_data_volume:
